@startuml

class MainController {
- colorScheme: ColorScheme
- paintBoard()
}

note left of MainController::paintBoard
colorScheme.render()
end note

interface ColorScheme {
+ render(): Color
}

class ClassicColorScheme {
+ render(): Color
}

class HighContrastColor {
+ render(): Color
}

class SplatoonColor {
+ render(): Color
}

MainController o--> ColorScheme
ColorScheme <|.. ClassicColorScheme
ColorScheme <|.. HighContrastColor
ColorScheme <|.. SplatoonColor

@enduml
