@startuml

class TetrisView {
- currentGameMode: GameMode
+ setGameMode(GameMode)
+ runGame()
}

note left of TetrisView::runGame
onGameStart()
while not checkGameEnd():
    tick()
onGameEnd()
end note

class GameMode {
- PieceGenerator generator
+ onGameStart()
+ onGameEnd()
+ checkGameEnd(): boolean
+ tick()
}

note right of GameMode
checkGameEnd() returns whether maximum height is reached
tick() picks a piece from the random generator
end note

class TimeLimitedMode {
- currentTime
- timeLimit
+ checkGameEnd(): boolean
}

note bottom of TimeLimitedMode
checkGameEnd() also checks whether time limit is reached
end note

class GodMode {
+ checkGameEnd(): boolean
+ tick()
}

note bottom of GodMode
checkGameEnd() always returns false
tick() pops up a window to let user select a piece to generate
end note

TetrisView o--> GameMode
GameMode <|-- GodMode
GameMode <|-- TimeLimitedMode

@enduml