@startuml


class TetrisBoard {
- notifyAll()
- onRowClear()
- observers: List[Observer]
+ addObserver(Observer)
+ removeObserver(Observer)
}

note right of TetrisBoard::onRowClear
calls notifyAll()
end note

interface ScoreObserver {
+ getScore(): int
+ update(TetrisBoard)
}

class DefaultScoreObserver {
+ getScore(): int
+ update(TetrisBoard)
}

class ComboScoreObserver {
+ getScore(): int
+ update(TetrisBoard)
}


TetrisBoard *--> ScoreObserver
ScoreObserver <|.. DefaultScoreObserver
ScoreObserver <|.. ComboScoreObserver

@enduml