@startuml

interface RotationState {
+ getRotationOffset(Piece, MoveType): Point
}

enum SuperRotationState {
+ getRotationOffset(Piece, MoveType): Point
}

class BasicRotationState {
+ getRotationOffset(Piece, MoveType): Point
}

class Model {
+ currentState: RotationState
+ modelTick(MoveType)
}

note right of Model::modelTick
Calls RotationState.getRotationOffset()
end note

RotationState o--> Model
SuperRotationState ..|> RotationState
BasicRotationState ..|> RotationState

@enduml