@startgantt

projectscale daily zoom 2

Project starts 2022-11-25

[Sprint 1] is colored in GreenYellow
[Sprint 1] starts 2022-11-25
[Sprint 1] ends 2022-12-1

[Framework design] starts at [Sprint 1]'s start
[Framework design] ends 2022-12-1

[Score calculation] starts 2022-11-26
[Score calculation] ends 2022-12-1

[Piece generator] starts at [Sprint 1]'s start
[Piece generator] lasts 3 days

[Super Rotation System] starts at [Piece generator]'s end
[Super Rotation System] ends 2022-12-1

[Colorscheme] starts at 2022-11-27
[Colorscheme] lasts 2 days

[Sprint 2] is colored in GreenYellow
[Sprint 2] starts at [Sprint 1]'s end
[Sprint 2] ends 2022-12-5

[Score calculation (cont)] starts at [Score calculation]'s start
[Score calculation (cont)] ends 2022-12-3

[Piece preview] starts at [Score calculation (cont)]'s end

[Timed mode] starts at [Score calculation (cont)]'s end
[Timed mode] lasts 2 days

[Super Rotation System (cont)] starts at [Super Rotation System]'s start
[Super Rotation System (cont)] ends at 2022-12-3

[Game mode] starts at [Sprint 2]'s start
[Game mode] ends at 2022-12-3

[Flexible view] starts at [Sprint 2]'s start
[Flexible view] ends 2022-12-5

[Hold] starts at 2022-12-4
[Line count mode] starts at [Hold]'s end


[Lock delay] starts at [Sprint 2]'s start

[Ghost piece] starts at [Lock delay]'s end
[Ghost piece] lasts 2 days

[Tetris effect] starts at [Ghost piece]'s end

[Sprint 3] is colored in GreenYellow
[Sprint 3] starts at [Sprint 2]'s end
[Sprint 3] ends 2022-12-7

[Tests] starts at [Sprint 3]'s start
[Tests] lasts 2 days

[Documentation] starts at [Sprint 3]'s start
[Documentation] lasts 2 days

[Project completed] happens at [Sprint 3]'s end
@endgantt